version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: db
    env_file: ./docker/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: backend:latest
    container_name: backend
    command: bash -c "sleep 4 && sh ./docker/entrypoint.sh"
    env_file:
      - ./docker/.env
    volumes:
      - .:/code
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
